require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChallengesController do

  # This should return the minimal set of attributes required to create a valid
  # Challenge. As you add validations to Challenge, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString", "description" => "My Description" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChallengesController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  let!(:user) { create(:user) }

  before do
    sign_in(user)
  end

  describe "GET index" do
    context "logged in" do
      it "assigns all challenges as @challenges" do
        challenge = user.challenges.create! valid_attributes
        get :index, {}, valid_session
        assigns(:challenges).should eq([challenge])
        expect(assigns(:challenges).map(&:user)).to eq([user])
      end

      it "does not load other user's todo lists" do
        other_challenge = Challenge.create!(valid_attributes.merge(user_id: create(:user).id))
        get :index, {}, valid_session
        expect(assigns(:challenges)).to_not include(other_challenge)
      end
    end
  end

  describe "GET show" do
    it "assigns the requested challenge as @challenge for the logged in user" do
      challenge = user.challenges.create! valid_attributes
      get :show, {:id => challenge.to_param}, valid_session
      assigns(:challenge).should eq(challenge)
      expect(assigns(:challenge).user).to eq(user)
    end
  end

  describe "GET new" do
    it "assigns a new challenge as @challenge for the logged in user" do
      get :new, {}, valid_session
      assigns(:challenge).should be_a_new(Challenge)
      expect(assigns(:challenge).user).to eq(user)
    end
  end

  describe "GET edit" do
    it "assigns the requested challenge as @challenge" do
      challenge = user.challenges.create! valid_attributes
      get :edit, {:id => challenge.to_param}, valid_session
      assigns(:challenge).should eq(challenge)
      expect(assigns(:challenge).user).to eq(user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Challenge" do
        expect {
          post :create, {:challenge => valid_attributes}, valid_session
        }.to change(Challenge, :count).by(1)
      end

      it "assigns a newly created challenge as @challenge" do
        post :create, {:challenge => valid_attributes}, valid_session
        assigns(:challenge).should be_a(Challenge)
        assigns(:challenge).should be_persisted
      end

      it "redirects to the created challenge" do
        post :create, {:challenge => valid_attributes}, valid_session
        response.should redirect_to(Challenge.last)
      end

      it "creates a todo list for the current user" do
        post :create, {:challenge => valid_attributes}, valid_session
        challenge = Challenge.last
        expect(challenge.user).to eq(user)
      end

      it "does not allow users to create challenges for other users" do
        other_user = create(:user)
        post :create, {:challenge => valid_attributes.merge(user_id: other_user.id)}, valid_session
        challenge = Challenge.last
        expect(challenge.user).to eq(user)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved challenge as @challenge" do
        # Trigger the behavior that occurs when invalid params are submitted
        Challenge.any_instance.stub(:save).and_return(false)
        post :create, {:challenge => { "title" => "invalid value" }}, valid_session
        assigns(:challenge).should be_a_new(Challenge)
        expect(assigns(:challenge).user).to eq(user)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Challenge.any_instance.stub(:save).and_return(false)
        post :create, {:challenge => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested challenge" do
        challenge = user.challenges.create! valid_attributes
        # Assuming there are no other challenges in the database, this
        # specifies that the Challenge created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Challenge.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => challenge.to_param, :challenge => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested challenge as @challenge" do
        challenge = user.challenges.create! valid_attributes
        put :update, {:id => challenge.to_param, :challenge => valid_attributes}, valid_session
        assigns(:challenge).should eq(challenge)
        expect(assigns(:challenge).user).to eq(user)
      end

      it "redirects to the challenge" do
        challenge = user.challenges.create! valid_attributes
        put :update, {:id => challenge.to_param, :challenge => valid_attributes}, valid_session
        response.should redirect_to(challenge)
      end
    end

    describe "with invalid params" do
      it "assigns the challenge as @challenge" do
        challenge = user.challenges.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Challenge.any_instance.stub(:save).and_return(false)
        put :update, {:id => challenge.to_param, :challenge => { "title" => "invalid value" }}, valid_session
        assigns(:challenge).should eq(challenge)
      end

      it "re-renders the 'edit' template" do
        challenge = user.challenges.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Challenge.any_instance.stub(:save).and_return(false)
        put :update, {:id => challenge.to_param, :challenge => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested challenge" do
      challenge = user.challenges.create! valid_attributes
      expect {
        delete :destroy, {:id => challenge.to_param}, valid_session
      }.to change(user.challenges, :count).by(-1)
    end

    it "redirects to the challenges list" do
      challenge = user.challenges.create! valid_attributes
      delete :destroy, {:id => challenge.to_param}, valid_session
      response.should redirect_to(challenges_url)
    end
  end

end
